# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2d1b8be8b96f961b13b3bca5a80ccb5830fd7b07df1739c4cd78b1a7bd09881432414dd2623874da19ebb920570a3c4e38b2aa808dc3e6fea38a24620104df9c

test:
  secret_key_base: 0ff77919eef1a5295f3fed70b1e4afd351bbb2ddad5d741b12c97a0be2b863f474dba4c326a74d622cb20245e63656ec05d03b2621268e874c8eacee08d09e25

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
